In [1]:
import pandas as pd

In [2]:
test = "this is a test"

In [3]:
test

'this is a test'

In [1]:
import pandas as pd
cali = pd.read_csv('../data/scrape_dm_cali.csv')
mich = pd.read_csv('../data/scrape_dm_mich.csv')
ny = pd.read_csv('../data/scrape_dm_ny.csv')
ohio = pd.read_csv('../data/scrape_dm_ohio.csv')
texas = pd.read_csv('../data/scrape_dm_texas.csv')
tweets = pd.concat([cali, mich, ny, ohio, texas])
tweets

,tweet_id,username,text,tweet_date,search_term,city,lat,long,radius,query_start
0,710245730590404608,TTWN SF Bay Area,Power outage in Cupertino #BayArea #Traffic ht...,2016-03-16 23:25:52,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
1,708811502241734656,San Jose Now,WEATHER ALERT: Flash flood watch in Bay Area a...,2016-03-13 00:26:45,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
2,706856719733776384,San Jose Now,Power outages:30 in San Francisco154 on Penins...,2016-03-07 14:59:09,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
3,726876023573204993,San Jose Now,Power outage in Fremont. Several intersections...,2016-05-01 20:48:43,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
4,724681945095888897,San Jose Now,"East Bay power outages also affects BART, UC B...",2016-04-25 19:30:14,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
...,...,...,...,...,...,...,...,...,...,...
3686,1138224668207407106,Katy Blakey,If — like me — you wondered what to do about t...,2019-06-10 23:21:22,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3687,1138224130631843840,T R E Y,This #dallas #poweroutage has gone to far the ...,2019-06-10 23:19:14,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3688,1138140304341635073,Charity Advertising & Marketing Partners,"Can’t stop, Won’t stop #dallasweather #thunde...",2019-06-10 17:46:08,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3689,1138102344728666113,Eisemann Center,"Power, AC & WiFi if anyone needs a place to “c...",2019-06-10 15:15:18,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3690,1137919777261985792,Patrick Ptomey,Eating meatballs in the dark. #DallasStorm #po...,2019-06-10 03:09:51,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01

In [24]:
test = cali.loc[89]['username']

In [25]:
test

'☮AnitaLoverOfPeace☮'

In [43]:
#for i in cali['text']:
    #print(i)
    #print('---------------------------------------------------------------------')

In [29]:
import re
import string

In [27]:
def clean_str(string):
    string = string.lower()
    url_pattern = r'((http|ftp|https):\/\/)?[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;:/~\+#]*[\w\-\@?^=%&amp;/~\+#])?'
    string = re.sub(url_pattern, ' ', string)
    string = re.sub(r"\n", "", string)    
    string = re.sub(r"\r", "", string) 
    #string = re.sub(r"[0-9]+", "", string)
    string = re.sub(r'[^\w\s]','', string)    
    
    return string.strip()

In [34]:
tweets

,tweet_id,username,text,tweet_date,search_term,city,lat,long,radius,query_start
0,710245730590404608,TTWN SF Bay Area,Power outage in Cupertino #BayArea #Traffic ht...,2016-03-16 23:25:52,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
1,708811502241734656,San Jose Now,WEATHER ALERT: Flash flood watch in Bay Area a...,2016-03-13 00:26:45,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
2,706856719733776384,San Jose Now,Power outages:30 in San Francisco154 on Penins...,2016-03-07 14:59:09,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
3,726876023573204993,San Jose Now,Power outage in Fremont. Several intersections...,2016-05-01 20:48:43,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
4,724681945095888897,San Jose Now,"East Bay power outages also affects BART, UC B...",2016-04-25 19:30:14,power outage,San Jose,37.332300,-121.853394,10mi,2016-01-01
...,...,...,...,...,...,...,...,...,...,...
3686,1138224668207407106,Katy Blakey,If — like me — you wondered what to do about t...,2019-06-10 23:21:22,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3687,1138224130631843840,T R E Y,This #dallas #poweroutage has gone to far the ...,2019-06-10 23:19:14,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3688,1138140304341635073,Charity Advertising & Marketing Partners,"Can’t stop, Won’t stop #dallasweather #thunde...",2019-06-10 17:46:08,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3689,1138102344728666113,Eisemann Center,"Power, AC & WiFi if anyone needs a place to “c...",2019-06-10 15:15:18,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01
3690,1137919777261985792,Patrick Ptomey,Eating meatballs in the dark. #DallasStorm #po...,2019-06-10 03:09:51,#poweroutage,Dallas,32.776665,-96.796989,15mi,2016-01-01

In [35]:
tweets['text'] = tweets['text'].map(clean_str)

In [37]:
tweets['text']

0               power outage in cupertino bayarea traffic
1       weather alert flash flood watch in bay area am...
2       power outages30 in san francisco154 on peninsu...
3       power outage in fremont several intersections ...
4       east bay power outages also affects bart uc be...
                              ...
3686    if  like me  you wondered what to do about the...
3687    this dallas poweroutage has gone to far the pa...
3688    cant stop wont stop  dallasweather thunderstor...
3689    power ac  wifi if anyone needs a place to chil...
3690    eating meatballs in the dark dallasstorm power...
Name: text, Length: 20100, dtype: object

In [39]:
tweets['username'] = tweets['username'].map(clean_str)

In [40]:
tweets['name_and_tweet'] = tweets['username'] + " " +tweets['text']

In [44]:
#for i in tweets['name_and_tweet']:
    #print(i)
    #print('--------------------------------------------------------')